CC     = gcc
CFLAGS = -Wall -g 
# -Wextra

#gera o executável
all: main.o # arq.o $(CC) -o tyf24 main.o #  arq.o
	$(CC) -o tyf24 main.o

#arq.o: arq.c arq.h $(CC) -c $(CFLAGS) arq.c

clean:
	rm -f *.o *~ 